import React from 'react'
import './componentStyles/home.css'

function Home() {
  return (
    <div>
        <div>
            <h1>Home</h1>
            <p>
                <img className='imgfloat' src="https://www.bhg.com/thmb/3Vf9GXp3T-adDlU6tKpTbb-AEyE=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/white-modern-house-curved-patio-archway-c0a4a3b3-aa51b24d14d0464ea15d36e05aa85ac9.jpg" alt="" />
            Home is considered as a place where you were brought up, which is related to the childhood memories, toys, favorite dishes, and traditions. Sometimes it happens for those international students while in the middle of the school day they have an unrestrained desire to go home. They close their eyes and see unforgettable masterpieces – a kitchen, a cozy bedroom, a living room, a bathroom, or soft carpet under the feet. It is related to their best memories, family, relatives, and history. Generally, these images are the houses of our grandparents or parents. In these spaces the family gathers and has a wonderful time together. This place brings back warm memories about the childhood and family holidays. Even music and flavors may make you think about this kind of home. These are the things that any person may miss when he is away from home for educational reasons.
            In fact, close relations to home cause the feeling of homesickness. In order to find an academic opportunity abroad international students leave their homes, families, and friend. Being in a different country they grieve for the places, objects, people, buildings, social networks and culture. In spite of modern technologies, which give people ability to speak to their relatives, this feeling is very common for international students who constitute a special group of students all over the globe. It may affect the person’s behavior and mental well being. Those students often miss every single object at their home. And that is why home is a varied and rich union of family and personal objects.
            Some people evaluate objects found at home. Very often a guest cannot notice special elements of design which were developed by one of the family members, furniture or decoration, made by somebody of the relatives, pictures or valuable for heart things which are passed from generation to generation. Individuals exhibit very strong connections and relations to personal mementos. Even rooms, whether it is a kitchen or living room, is one of the mementos which bring their memories back. In this way, Home may express different aspects of our past. It is the place directly connected with our biography, as here we had physical and special representation.
            Such a house or an apartment may have a link to your past at the same time being a door to the future. In such a house you feel comfortable; you come back to the house willingly and with great desire. For someone it may be a huge cottage, or a house at the seaside, for others a tiny one room flat with a kitchen. The size of your home does not mean anything. The things inside it mean all. It should be associated with physical state in which we feel mentally relaxed. The memories, which arise when we think about our country as a home, become related to the house itself, a building where we grew up and that is when the feeling of homesick begins. In this case, there are several reasons of being homesick and culture shock is one of them. International students, especially those who do not understand the language well, and who come from countries with considerably different cultural backgrounds, have troubles adjusting to the surrounding environment. The greater the differences between the host culture and the native culture, the stronger feeling of homesickness will the student experience. Culture shock causes desire for family and familiar environment. The second reason is time difference, which sometimes makes communication with relatives almost impossible. They start feeling lonely expect the cases when they can make friends easily. Language is considered to be the third reason of homesickness. Sometimes international students do not speak perfectly, do not understand the professor, and cannot express their ideas. These factors may cause a great trouble for any international student.
            As a result, the effects include sadness, loneliness, sleeping problems, headaches, anxiety, isolation, and difficulties at the university or college. Unfortunately the feeling of homesickness is long lasting and may lead to social alienation. According to some studies, students who study far away from their houses experience the feeling of homesickness more often than those who study close to their parents Those who feel homesick often have poor progress in studying, get lower scores, and are more often depressed in comparison to students who are not homesick. Thus, home is a word, which embraces and has very vast meaning. It reflects our values and beliefs that are usually associated with the childhood, which is always deep in our memories. If anything reminds us about any aspect of beliefs or values, which were followed by the family, no doubt that you will immediately think about home. In this context home is defined by neighborhood and ethnicity.
            </p>
        
        </div>
    </div>
  )
}

export default Home;